version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - echo Build started on `date`
      - cd AWSServerless1
      - echo "Cleaning..."
      - dotnet clean -v q
      - echo "Publishing..."
      - dotnet publish -c Release -v q
      - mkdir dist
      - rm -rf dist/*
      - zip -j dist/deploy.zip AWSServerless1/bin/Release/netcoreapp3.1/publish/*
      - export BUCKET=lambda-deployment-artifacts-865075051780
      - aws cloudformation package --template-file AWSServerless1/serverless.template --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - AWSServerless1/serverless.template
    - outputtemplate.yml